# Generated by Django 4.1.7 on 2023-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0004_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=15),
        ),
    ]
