# Generated by Django 4.1.7 on 2023-03-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0006_section_inscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
