# Generated by Django 4.1.7 on 2023-03-26 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0007_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='section',
        ),
        migrations.RemoveField(
            model_name='representative',
            name='email',
        ),
        migrations.AddField(
            model_name='inscription',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ncl.course'),
        ),
        migrations.AddField(
            model_name='payment',
            name='courses',
            field=models.ManyToManyField(to='ncl.course'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='representative',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='representative',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='age_category',
            field=models.CharField(choices=[('A', '1 a 3 años de edad'), ('B', '4 a 6 años de edad'), ('C', '7 a 9 años de edad'), ('D', '10 a 12 años de edad'), ('E', 'Adolescente')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
