# Generated by Django 4.1.7 on 2023-03-26 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0009_agecategory_alter_student_age_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ncl.representative'),
        ),
    ]
