# Generated by Django 4.1.7 on 2023-03-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0010_alter_student_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
