# Generated by Django 4.1.7 on 2023-03-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0012_rename_courses_payment_course_course_teachers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
