# Generated by Django 4.1.7 on 2023-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0013_rename_teachers_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscription',
            name='course',
        ),
        migrations.AddField(
            model_name='inscription',
            name='course',
            field=models.ManyToManyField(to='ncl.course'),
        ),
    ]
