# Generated by Django 4.1.7 on 2023-04-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ncl', '0014_remove_inscription_course_inscription_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, to='ncl.teacher'),
        ),
    ]
